[package]
name = "mock-wikipedia-api"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
argh = "0.1"
axum = { version = "0.8.6", features = ["macros"] }
env_logger = "0.9"
http = "1.3.1"
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
